Home task #4
idunskiy/TestProject pull request #5
Opened 2020-04-25 13:16 UTC by idunskiy

2020-04-26 07:12 UTC, dbradul requested changes

2020-04-26 07:12 UTC, dbradul commented on lesson_03.py
> +def get_unique_firstnames():
Отлично, что использовали возможности SQL для этого

2020-04-26 07:12 UTC, dbradul commented on lesson_03.py
> +def get_filtered_by_state_and_city():
Для фильтрации нужно получить значения города и штата из запроса клиента и передавать их в SQL-запрос в конструкцию `... WHERE City=... And State=...`.

2020-04-26 07:12 UTC, dbradul commented on lesson_03.py
> +    query = 'SELECT SUM(UnitPrice * Quantity) FROM invoice_items'
Здесь тоже отлично, что испоьзовали SQL

2020-04-26 09:09 UTC, idunskiy commented on lesson_03.py
> +def get_unique_firstnames():
А какие могли быть альтернативы? )

2020-04-26 09:13 UTC, idunskiy commented on lesson_03.py
> +def get_filtered_by_state_and_city():
Ок, это я доработаю.

2020-04-26 13:15 UTC, dbradul commented on lesson_03.py
> +def get_unique_firstnames():
Можно было пройти по полученным записям и добавлять их в set: 
```
unique_names = set()
for record in records:
    unique_names.add(record[0])
```
Эта структура поддерживает уникальность значений.

2020-05-01 07:24 UTC, idunskiy commented
Not relevant anymore, merged changes with another pull request.

2020-05-01 07:24 UTC, closed without merging